#!/usr/bin/env ansible-playbook
---
# If you like to play: ./ansible/create.yml --skip-tags public_dns,letsencrypt
- hosts: localhost
  connection: local
  # gather_facts true because we need the public ip address
  gather_facts: true
  become: true
  # vars_files:
  # - ../cluster.yml
  vars:
    root_ca_passphrase: bobleponge!
  roles:
    - { role: sushy-tools }

  tasks:
  - name: Install sushy-tools
    import_role:
      name: sushy-tools
      tasks_from: main.yml
