#!/usr/bin/env ansible-playbook
---
- name: Create BMH resource for new OpenShift node
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    cluster_name: hubcluster-02
    pool_dir: "/var/lib/libvirt/images"
    vm: worker-1
    vcpus: 4
    ram_mb: 8192
    cleanup: no
    net: ovs-network

  tasks:
    - name: KVM Provision role
      include_role:
        name: ocp4_baremetalhost_kvm
      vars:
        vm_name: "{{ cluster_name }}-{{ vm }}"
        vm_net: "{{ net }}"
