# ---
# tasks file for kvm_provision
- name: Ensure requirements in place
  package:
    name:
    - libguestfs-tools
    - python3-libvirt
    state: present
  become: yes

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no
  become: yes

- name: Create qcow2 based disk for vm {{ vm_name }}
  command: "qemu-img create -o preallocation=metadata -f qcow2 {{ libvirt_pool_dir }}/{{ vm_name }}.qcow2 120G"
  become: yes
  when: "vm_name not in existing_vms.list_vms"

- name: Change qcow2 file ownership disk for vm {{ vm_name }}
  ansible.builtin.file:
    path: "{{ libvirt_pool_dir }}/{{ vm_name }}.qcow2"
    owner: qemu
    group: qemu
    mode: '0640'
  become: yes

- name: Define vm
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'vm-template.xml.j2') }}"
  when: "vm_name not in existing_vms.list_vms"
  become: yes

