---
# tasks file for system-initial-setup

- name: Configure dnsmasq for OCP
  template:
    dest: /etc/dnsmasq.d/ocp4.conf
    src: dnsmasq.conf.j2
  notify:
  - Start dnsmasq
  tags:
  - dnsmasq

- name: Preserve resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /etc/dnsmasq.resolv.conf
    force: no
  tags:
  - dnsmasq

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    force: no
    group: root
    owner: root
    mode: 0755
  loop:
  - /var/lib/dnsmasq/hostsfile
  - /var/lib/dnsmasq/addnhosts
  tags:
  - dnsmasq

- name: Open dhcp and dns n firewall
  ansible.posix.firewalld:
    service: "{{ item }}"
    zone: "{{ baremetal_zone }}"
    permanent: yes
    state: enabled
  loop:
  - dhcp
  - dns

#
# Use dynamic resolution
#
# - name: Use local server as dns resolver
#   community.general.nmcli:
#     conn_name: ovs-if-br-ext
#     dns4:
#     - 172.16.1.176
#     state: present
